### ISSUE TITLE
Display issues on 4k monitor

### ISSUE THREAD

**Issue by coltonTB** [arcticicestudio/nord-atom-ui#62] opened 2017-03-24 03:51 UTC
See screenshot:
![image](https://cloud.githubusercontent.com/assets/1873024/24279959/87875638-1023-11e7-8b81-6e6d5a2e710f.png)

This issue doesn't happen for other themes

**Comment by arcticicestudio** [comment] 2017-03-26 16:10
Thanks for your report 👍 
This is a strange issue. If other themes work fine it may be related to the currently unoptimized UI scaling of the theme.
I'll tag the issue as pending until the UI scale refactoring in #58 has been implemented and merged which may fix this issue too as a side effect.

Unfortunately I'm not able to reproduce it because of "Hardware" limitations 😆 (Maybe next week at work on a iMac).

**Comment by Acidfabric** [comment] 2017-04-14 12:33
Same problem on 1920x1080res, not apple monitor

![img](https://gyazo.com/72f87189dec153d9ce4c885d8cdf6202.png)

**Comment by arvindch** [comment] 2017-04-18 14:04
Yes, exact same issue here. Dell XPS 13 9350, with a 1920*1080 display at 100% scaling on Windows 10 (updated).

**Comment by arcticicestudio** [comment] 2017-04-18 18:00
Unfortunately I'm not able to reproduce this and I've currently no idea where the origin of this strange bug could be. It looks like there is a kind of margin to the text.

Can you please try to analyse the bright sections with the developer tools (`Ctrl` + `Shift` + `i`) and check if these are wrapped into a `<div>` or any other kind of element and if there are any CSS classes or IDs assigned to it? You can also create a DOM dump and post it in a archive file so I can debug it.

Also can you check if you have the *Full-Width Tab Sizing* theme setting disabled?
There have been several problems when this gets disabled and I think I'll have to remove it until #58 has been merged.
![](https://cloud.githubusercontent.com/assets/7836623/19620532/ef4ef634-987f-11e6-89bd-5dda9bcade88.png)

**Comment by arcticicestudio** [comment] 2017-04-28 20:09
I've done a small research and (luckily) it seems like the Nord theme is not the origin of this problem but Atom or more precisely Chromium contains a bug related to `div` rendering. It seems like these glitches are random so it is hard to reproduce this, but they appear with other Atom UI- and Syntax themes too.
See related issues [atom/atom #14318](https://github.com/atom/atom/issues/14318), [atom/atom #12634](https://github.com/atom/atom/issues/12634) and Chromium bug tracker ticket [#633805](https://bugs.chromium.org/p/chromium/issues/detail?id=633805).

**Comment by arcticicestudio** [comment] 2017-05-06 15:24
I close this since it seem to be Atom problem.
If there are solutions to fix this on the theme site feel free to reopen it.

**Closed by arcticicestudio** 2017-05-06 15:24 UTC
Labels: pending
