### ISSUE TITLE
Regexp groups in find/replace text field obscured by highlighting

### ISSUE THREAD

**Issue by gertsonderby** [arcticicestudio/nord-atom-ui#39] opened 2016-11-02 09:00 UTC
When typing in a regular expression in the find dialog, I encounter an unhappy interaction between Nord theme and Nord syntax - The plain-text contents of group matches (e.g. 'Le' in `Who (Le)* Foo`) are syntax highlighted white, and the background of the active search field is white. Hence the text is invisible. Selecting the text makes it visible again by virtue of the light grey selection highlight, but it does cause a small bit of irritation every now and then.

I'm not sure what the best solution here might be - a modification of the syntax highlighting when in a dialog field? A different focus highlight color for these fields?

**Comment by arcticicestudio** [comment] 2016-11-02 21:47
Thanks for your report, I'll take a look at it as sonn as possible.
Could you provide a test text, the regexp and maybe a screenshot please? This way it'll be easier for me to reproduce the scenario.

**Comment by gertsonderby** [comment] 2016-11-02 23:09
Here's as detailed a replication report as I can make.

Steps:
1: Atom with Nord UI and syntax themes
2: Open a file (any text file type, including a new or empty file)
3: Open find or find-in-files dialog
4: Switch on regexp search
5: Focus on search field
6: Enter the following regexp: `(test)`

Expected:
Regexp search string should be fully visible.

Actual:
While search field focused, Only the parentheses are visible, the string 'text' is white on white.
If focus is removed, regexp is fully visible.

**Comment by arcticicestudio** [comment] 2016-11-06 22:01
Thanks for your detailed feddback, this will be fixed as soon as I've finished the refactoring of my previous theme packages and also got notified about this by another user as seen by the cross-repository reference marker above.

**Comment by arcticicestudio** [comment] 2016-11-15 16:52
I was able to reproduce this, but its a bit tricky to fix this due to the fact that the highlighting depends on the selected syntax theme. The regexp pattern inherits the CSS rules defined by the current syntax theme which is the javaScript `js` selector in your example (`(test)`).

It is possible to set the text color for the focused input to the default dark color, **but** this will remove all other syntax highlighting colors of this pattern e.g. if the current syntax theme uses a red color for braces.

![ghi-43-scrcast-workaround](https://cloud.githubusercontent.com/assets/7836623/20314774/9d3126c6-ab5b-11e6-9fe2-feb24e7ba528.gif)

I added an theme setting in #43 to use a darker form-focusing effect which can help to avoid this bug too.

![ghi-39-scrcast-reference-ghi-43](https://cloud.githubusercontent.com/assets/7836623/20314902/3658bd28-ab5c-11e6-9e25-c23174ac2e27.gif)


Anyway, I'll add the dark text workaround described above and you can decide if you want to use the new theme setting if you want to have colored syntax highlighting for regexp searchs too.

**Comment by arcticicestudio** [comment] 2016-11-16 17:40
Released in :package: version [0.8.0](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.8.0)

**Closed by arcticicestudio** 2016-11-16 17:40 UTC
Labels: bug
