### ISSUE TITLE
Tree view is light

### ISSUE THREAD

**Issue by khinbaptista** [arcticicestudio/nord-atom-ui#59] opened 2017-03-07 20:23 UTC
I like the theme a lot, but I cannot use it like this :/

![image](https://cloud.githubusercontent.com/assets/7837147/23676100/578f9e0c-035a-11e7-8a2d-a41c99002032.png)

**Comment by st-andrew** [comment] 2017-03-07 21:24
Looks like you set the Syntax theme to Nord Atom but not the UI Theme.  Make sure you do both.

**Comment by arcticicestudio** [comment] 2017-03-08 14:31
The tab bar is colored correct, so the Nord Atom UI theme seem to be set.
I've never had this issue. Are you able to reproduce this behavior?

**Comment by arcticicestudio** [comment] 2017-04-01 07:12
@khinbaptista Are you still affected by this problem (reproduceable) or can this issue be marked as resolved?

**Comment by khinbaptista** [comment] 2017-04-07 13:43
it only happened to me in windows, I'll try to reproduce it

**Comment by khinbaptista** [comment] 2017-04-07 13:47
yes, it still happens, but I just noticed it happens to other themes as well, it's probably not a nord issue.
![image](https://cloud.githubusercontent.com/assets/7837147/24802782/94c255a2-1b7f-11e7-9f32-a5cf78a6ac40.png)

**Comment by arcticicestudio** [comment] 2017-04-07 18:43
Thanks for the test, maybe you can create a issue in the ⚛️ Atom [`tree-view`](https://github.com/atom/tree-view) core package repository so this can be adressed.

**Closed by arcticicestudio** 2017-04-07 18:43 UTC
Labels: pending
